package com.example.sr2_2020.svt2021.projekat.model;

public enum ReportReason {

    BREAK_RULES, HARASSMENT, HATE, SHARING_PERSONAL_INFORMATION, IMPERSONATION, COPYRIGHT_VIOLATION,
    TRADEMARK_VIOLATION, SPAM, SELF_HARM_OR_SUICIDE, OTHER
}
